### ISSUE TITLE
I need help ! 

### ISSUE THREAD

**Issue by TheJRJ** [steam-account-creator/Steam-Account-Generator#65]
Hello, I am an admirer of your work, my English will seem a little strange, but I'm using google translate, because I'm Brazilian, but this is not the case.

I use version 1.1.3.3 for windowns, but I have to put an email, because when I mark to randomly generate an email, the emails are not generated (it does not generate a domain, it looks like: themen@).

So I'm being forced to create email's so I can generate the accounts ...

So I downloaded the DEV-windows-2.1.1 version, I downloaded it to see if the problem had been fixed, it probably should have been, but I came across another problem in this new version (a problem that in the previous version does not happen).

When trying to generate the accounts of the following error: Use custom domain. No public domain available at this time!

This is probably due to the new proxy features, and maybe I don't know how to use it, I need some help knowing how to use it and what to do to stop this problem.

I want to generate accounts with random emails and be able to generate accounts without errors, please help me!

Thanks in advance ! I enjoy your work.

![image](https://user-images.githubusercontent.com/57741229/68827347-621efd00-0680-11ea-8023-392d778385a7.png)

**Comment by despa1r1337** [comment]
hi, use random mail you do not learn, because free domains are completely blocked in the steam system.  

but there are 2 solutions: 
1) use your mailbox, just register on ‘gmail.com’ and use this instruction - https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Using-gmail

2) buy a domain, after the purchase to register in the settings Mx record ' mailhost.root.sx'

**Comment by despa1r1337** [comment]
No any replay after 3 days. Gonna close issue. If any related questions, reopen issue.
