### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by NieKozinho** [steam-account-creator/Steam-Account-Generator#87]
Steam has disallowed your IP making this account

Testing on my IP and VPN

**Comment by despa1r1337** [comment]
> Steam has disallowed your IP making this account
> 
> Testing on my IP and VPN

restart your internet

**Comment by EduAlves27** [comment]
@verdammnis I have the same issue, already tried to restart internet but still happening...

**Comment by verdammnis** [comment]
> 

wait 24h

**Comment by EduAlves27** [comment]
> > @verdammnis I have the same issue, already tried to restart internet but still happening...
> 
> wait 24h

I already waited 24h a lot of times, but still giving error...

**Comment by EduAlves27** [comment]
After I try to create too much accounts I get a infinite loop with captcha, but if I wait 24h the loop disappears, however when creating accounts after that, I  get the error message "steam has disallowed your IP making this account" and if I try too much times infinite captcha loop again and so that is a cycle :(

**Comment by verdammnis** [comment]
> After I try to create too much accounts I get a infinite loop with captcha, but if I wait 24h the loop disappears, however when creating accounts after that, I get the error message "steam has disallowed your IP making this account" and if I try too much times infinite captcha loop again and so that is a cycle :(

i can't help you, this project is not updated.  try with  https://accgen.cathook.club/
